apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: flipbook-converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: flipbook-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://backend-service:8000"
        - name: NEXT_PUBLIC_CDN_URL
          valueFrom:
            secretKeyRef:
              name: flipbook-secrets
              key: R2_PUBLIC_URL